# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir D:/AC2/mipscorect/mipscorect.cache/wt [current_project]
set_property parent.project_path D:/AC2/mipscorect/mipscorect.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo d:/AC2/mipscorect/mipscorect.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  D:/AC2/mipscorect/mipscorect.srcs/sources_1/imports/AC2/SSD.vhd
  D:/AC2/mipscorect/mipscorect.srcs/sources_1/imports/AC2/MPG.vhd
  D:/AC2/mipscorect/mipscorect.srcs/sources_1/new/MIPS.vhd
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/AC2/mipscorect/mipscorect.srcs/constrs_1/imports/AC2/NexysA7_test_env.xdc
set_property used_in_implementation false [get_files D:/AC2/mipscorect/mipscorect.srcs/constrs_1/imports/AC2/NexysA7_test_env.xdc]


synth_design -top MIPS -part xc7a100tcsg324-1


write_checkpoint -force -noxdef MIPS.dcp

catch { report_utilization -file MIPS_utilization_synth.rpt -pb MIPS_utilization_synth.pb }
